# Generated by Django 2.2.3 on 2019-08-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePower',
            fields=[
                ('meter_number', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('Meter_type', models.CharField(max_length=50)),
                ('units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
